urls.py
from django.urls import path
from django.conf import settings

from .import views

app_name = 'books'

urlpatterns =[
        path('', views.index, name='index'),
        path('books/', views.BookListView.as_view(), name='books'),
        path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
        path('authors/', views.AuthorListView.as_view(), name='authors'),
        path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),]


urlpatterns += [
        path('mybooks/', views.WishedBooksByUserListView.as_view(), name='my_wished'),
        path('myview/', views.WishedBooksAllUsersListView.as_view(), name='myview'),
        path('book/<int:pk>/renew/', views.renew_book_librarian, name='renew_book_librarian'),
        path('book/<int:pk>/status/', views.wish_book, name = 'status')]

urlpatterns += [
        path('authors/create/', views.AuthorCreate.as_view(), name='author_create'),
        path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
        path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
        ]


models.py
from django.db import models
from django.urls import reverse #to generate URLS by reverse URL patterns
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction"""
    name = models.CharField(max_length=200)
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        """string for representing the Model object (in Admin site etc.) """
        return self.name
    
    
class Book(models.Model):
    """Model representing a book"""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, blank=True)
    genre = models.ManyToManyField(Genre)
    pub_house = models.CharField(max_length=200)
    pub_date = models.CharField(max_length=200, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    CATEGORY = (
            ('r','roman'), 
            ('pv','povestiri'), 
            ('e','eseuri'),
            ('pz','poezie'), 
            ('nf','non-fiction'),
            ('t','teatru'))    
    
    category = models.CharField(max_length=2, choices=CATEGORY, blank=True)
    
    
    def display_genre(self):
       """Creates a string for the genre. This is required to display genre in Admin"""
       return ', '.join([genre.name for genre in self.genre.all()[:3]])
       
    display_genre.short_description = 'Genre'
   
    def __str__(self):
        """String for representing the Model object"""
        return self.title
    
    def get_absolute_url(self):
        return reverse('books:book_detail', args=[str(self.id)])
    
    
from datetime import date

class Status(models.Model):
    """Model representing the book status"""
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    wisher = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    due_back = models.DateField(null=True, blank=True)
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    
    GIVEAWAY_STATUS = (
            ('av','Cu chef de ducă'), 
            ('wished', 'Dorită'), 
            ('gone','Pooof! Nu mai e!'))

    status = models.CharField(max_length=10, default='av', choices=GIVEAWAY_STATUS)
    
    class Meta:
        permissions = (("can_mark_wished", "Set book as wished"),)
        verbose_name_plural = "statuses"
        
    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    
    class Meta:
        ordering = ['first_name', 'last_name']
    
    def get_absolute_url(self):
        return reverse('books:author_detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.first_name}, {self.last_name}'
    

templates/author_confirm_delete.html

{% extends "books/base_generic.html" %}

{% block content %}
<h1> Șterge autorul </h1>
<p>Ești sigur că vrei să ștergi autorul: {{ author }}? </p>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Da, șterge.">
  </form>
{% endblock %}

templates/author_create_form.html
{% extends "books/base_generic.html" %}

{% block content %}

 <form action="" method="POST">
   {% csrf_token %}
     <table>
       {{form.as_table}}
     </table>
     <input type="submit" value="Crează">
  </form>
{% endblock %}

templates/author_detail.html
{% extends "books/base_generic.html" %}

{% block content %}

  <h1><strong>Autor: {{author}} </strong></h1>
  <div style="margin-left:20px, margin-top:20px">
  <h4><strong>Cărți: </strong></h4>
  <dl>
  {% for book in author.book_set.all %}
    <dt><a href="{% url 'books:book_detail' book.pk %}"> {{book.title}}</a></dt>
    <dd> {{book.summary}}</dd>
  </dl>
  {% endfor %} 
  </div>
{% endblock %}

templates/author_list.html
{% extends "books/base_generic.html" %}

{% block content %}
    <h1>Listă autori</h1>
    {% if author_list %}
    <ul>
      {% for author in author_list %}
         <li>
         <a href="{% url 'books:author_detail' author.pk %}">{{author.first_name}} {{author.last_name}}</a>
         </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>N-avem nici un autor cu numele ăsta!</p>
    {% endif %}
{% endblock %}

templates/author_update_form.html

{% extends "books/base_generic.html" %}

{% block content %}

  <form action="" method="POST">
    {% csrf_token %}
      <table>
        {{form.as_table}}
      <input type="submit" value="Modifică">
    </table>
  </form>
{% endblock %}

templates/book_create_form.html
{% extends "books/base_generic.html" %}

{% block content %}

 <form action="" method="POST">
   {% csrf_token %}
     <table>
       {{form.as_table}}
     </table>
     <input type="submit" value="Crează">
  </form>
{% endblock %}

templates/book_detail.html
{% extends "books/base_generic.html" %}

{% block content %}
    <h1>Titlu: {{book.title}}</h1>
    <ul>
      <p><strong>Autor:</strong>
      <a href="{% url 'books:author_detail' book.author.pk %}"> {{book.author}} </a></p>
      <p><strong>Sumar:</strong> {{book.summary}}</p>
      <p><strong>Categorie:</strong> {% for category in book.category %}
      {{book.get_category_display}} {% endfor %}</p>
      <p><strong>Gen:</strong> {% for genre in book.genre.all %} {{genre}}
      {% if not forloop.last %}, {% endif %} {% endfor %}</p>
      <p><strong>Ediție: </strong> {{ book.pub_house }}</p>
      <p><strong>Posesor: </strong> {{ book.owner }}</p>
      <p><strong>Status: </strong> 
      {% for status in book.status_set.all %}
      {% if status.status == 'av' %} 
      <a href="{% url 'books:status' status.pk %}">{{status.get_status_display}}</a>
        {% if user.is_authenticated %}
            <form action="" method="post"> 
            {% csrf_token %}
            <p>O vrei? Marchez-o ca dorită! - {{form}}</p> 
            <input type="submit" value="OK"> 
            </form>
            {% else %}
            <p>Ai uitat să te autentifici! </p>
            <p>Mergi, te rog, la login și apoi revino. </p>
            {% endif %}
      {% else %} {{status.get_status_display}} -- (<strong>{{status.wisher}}</strong>; Termen: {{status.due_back}})</p>
        {% endif %}
        {% endfor %} 
    </ul>
    
{% endblock %}

templates/book_list.html
{% extends "books/base_generic.html" %}

{% block content %}
    <h1>Listă cărți</h1>
    {% if book_list %}
    <ul>
      {% for book in book_list %}
         <li>
         <a href="{% url 'books:book_detail' book.pk %}">{{book.title}}</a> - {{book.author}}
         </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>N-avem nici o carte de acest fel</p>
    {% endif %}
{% endblock %}

templates/index.html
{% extends "books/base_generic.html" %}
{% block content %}

<h1>Runaway books</h1>
<p>Aici s-au adunat astea de așteaptă doar un semn să o întindă.  
<br>Cică e aglomerație mare. Sufocant, de-a dreptul...
<br>Cică au ele un dor, așa, să-și desfacă aripile, să bucure alți oameni, alte minți.
<br>Așa că aruncați o privire, poate mă scăpați de ele. Una câte una, sau mai multe deodată. Cum vă place.</p>

<h2>Catalog dinamic</h2>
<p>Astea-s cifrele:</p>
<ul>
<li><strong>Cărți: </strong>{{num_books}}</li>
<li><strong>Autori: </strong>{{num_authors}}</li>
<li><strong>Cărți disponibile: </strong>{{num_available_books}}</li>
</ul>

<p>Ai vizitat această pagină {% if num_visits == 1 %} odată {% else %} de {{num_visits}} ori. </p>
{% endif %}
{% endblock %}


templates/manage_create.html
{% extends "books/base_generic.html" %}

{% block content %}

 <form action="" method="POST">
   {% csrf_token %}
     <table>
       {{form_book.as_table}}
       {{form_author.as_table}}
     </table>
     <input type="submit" value="Crează">
  </form>

{% endblock %}

templates/renew_book_librarian.html

{% extends "books/base_generic.html" %}

{% block content %}

<h1>Prelungire: {{status.book.title}}</h1>
<p>Doritor: {{ status.wisher }}</p>
<p{% if status.is_overdue %} class="text-danger" {% endif %}> Termen: {{status.due_back}}</p>

  <form action="" method="post">
  {% csrf_token %}
  <table>
  {{form.as_table}}
  </table>
  <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/status.html

{% extends "books/base_generic.html" %}

{% block content %}

<h2>Titlu: {{status.book}}</h2>
{% if user.is_authenticated %}
<form action="" method="post"> 
    {% csrf_token %}
    <p>Vrei cartea asta? Marcheaz-o ca <strong>dorită</strong> - {{form}}</p> 
    <input type="submit" value="OK"> 
</form>
{% else %}
<p>Ai uitat să te autentifici! </p>
<p>Mergi, te rog, la login și apoi revino. </p>
{% endif %}
{% endblock %}

templates/status_list_whished_all_users.html

{% extends "books/base_generic.html" %}

{% block content %}

<h1>Toate cărțile dorite </h1>

  {% if status_list %}
  
  <ul>
    {% for status in status_list %}
    <li class="{% if status.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'books:book_detail' status.book.pk %}">{{ status.book}}</a> ({{ status.due_back}}) 
    {% if user.is_staff %} - {{ status.wisher }}{% endif %}
    {% if perms.book.can_mark_available %} - <a href="{% url 'books:renew_book_librarian' status.pk %}">Prelungire</a>{% endif %}
    </li>
  {% endfor %}
  </ul>
  
{% else %}

<p>N-am găsit nici o carte dorită!</p>
{% endif %}
{% endblock %}

templates/status_list_whished_user.html

{% extends "books/base_generic.html" %}

{% block content %}

  <h1> Cărți dorite </h1>

  {% if status_list %}
  <ul>
    {% for status in status_list %}
    <li class="{% if status.is_overdue %}text_danger{% endif %}">
      <a href="{% url 'books:book_detail' status.book.pk %}">{{ status.book.title }}</a> ({{ status.due_back }})
    </li>
    {% endfor %}
  </ul>

  {% else %}
    <p> N-am găsit nici o carte dorită!</p>
  {% endif %}
{% endblock %}